[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
optimizer = true
optimizer_runs = 1_000_000
ffi = true

[profile.ci]
verbosity = 3

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
